spring:
  application:
    name: board-mybatis

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/board_mybatis_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${db_username}
    password: ${db_password}

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml